databases:
  - name: trading-postgres
    databaseName: tradingbot
    user: unCodedTradingBot
    plan: starter
    region: oregon
    ipAllowList: []

services:
  # Trading Bot von Docker Hub
  - type: worker
    name: trading-bot
    env: docker
    image:
      url: docker.io/aureumvictoria/trading-bot-secure:latest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trading-postgres
          property: connectionString
      - key: POSTGRES_HOST
        fromDatabase:
          name: trading-postgres
          property: host
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        fromDatabase:
          name: trading-postgres
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: trading-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: trading-postgres
          property: password
      - key: DOCKER_ENV
        value: "true"
      # API Keys - User muss diese selbst setzen
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false

  # Telegram Bot von Docker Hub
  - type: worker
    name: telegram-bot
    env: docker
    image:
      url: docker.io/aureumvictoria/telegram-bot-secure:latest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trading-postgres
          property: connectionString
      - key: POSTGRES_HOST
        fromDatabase:
          name: trading-postgres
          property: host
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DB
        value: tradingbot
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: trading-postgres
          property: password
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_GROUP_ID
        sync: false
      - key: TELEGRAM_OWNER_ID
        sync: false
