databases:
  - name: tradingdb
    databaseName: tradingbot
    user: dbuser

services:
  - type: worker
    name: trading-bot
    env: docker
    image:
      url: docker.io/aureumvictoria/trading-bot-secure:latest
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: tradingdb
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: tradingdb
          property: port
      - key: POSTGRES_DB
        fromDatabase:
          name: tradingdb
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: tradingdb
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: tradingdb
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: tradingdb
          property: connectionString
      - key: DOCKER_ENV
        value: "true"
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false

  - type: worker
    name: telegram-bot
    env: docker
    image:
      url: docker.io/aureumvictoria/telegram-bot-secure:latest
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: tradingdb
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: tradingdb
          property: port
      - key: POSTGRES_DB
        fromDatabase:
          name: tradingdb
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: tradingdb
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: tradingdb
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: tradingdb
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_GROUP_ID
        sync: false
      - key: TELEGRAM_OWNER_ID
        sync: false